[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
gridit = "0.1.0"
itertools = "0.14.0"
nom = "8.0.0"
